changelog:
  exclude:
    labels:
      - "release-type/patch"
      - "release-type/minor"
      - "release-type/major"
  categories:
    - title: "FEAT"
      labels:
        - "feat"
    - title: "FIXES"
      labels:
        - "fix"
    - title: "SECURITY"
      labels:
        - "security"
    - title: "REFACTOR"
      labels:
        - "refactor"
    - title: "PERF"
      labels:
        - "perf"
    - title: "DB"
      labels:
        - "db"
    - title: "OTROS"
      labels:
        - "chore"
        - "style"
        - "test"
        - "docs"
        - "*"
